### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [gridscale/terraform-provider-gridscale#1]
Hey Team, 👋 My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the master branch at git commit `86f10f3`.

- [ ] All the acceptance tests are passing from our side, and you have 45% coverage across the providers. Which is great but we would love to get that above 50% or more!

- [x] In your website documentation there were just a few discrepancies between some of the resource arguments. In the IPV4 and IPV6 docs, the Name argument is listed as required, but in the resource code its defined at optional. The same is for the capacity argument in the storage resource. 

Since these are both small items, I’m going to move this provider forward to the next phase which is a technical review by a member of the HashiCorp’s Terraform engineering team. There are a few integrations ahead of you in the queue, so it will take a few weeks till someone gets to you.

**Comment by fkr** [comment]
Hi Chris,
thanks for the feedback. We'll tackle the two mentioned items shortly!
Thanks for the heads-up regarding the next step.

felix

**Comment by sharkwouter** [comment]
Pull request #2 should fix the issues with the documentation.

**Comment by sharkwouter** [comment]
The pull requests #3 and #4 should have increased the test coverage significantly. That means the issues mentioned here should be resolved.
