### ISSUE TITLE
Documentation Issues in Terraform Resources.

### ISSUE THREAD

**Issue by tmallikarjuna** [gridscale/terraform-provider-gridscale#102]
Hi,

I found that there is no argument support for public_net as mentioned here: https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/network#public_net. Please do correct it here.

Also, there is no uuid argument mentioned here in the same above document: 

Below is the reference for the uuid support available on network resource with variable 'id':

```
+ resource "gridscale_network" "network" {
      + change_time      = (known after apply)
      + create_time      = (known after apply)
      + delete_block     = (known after apply)
      + id               = (known after apply)
      + l2security       = false
      + location_country = (known after apply)
      + location_iata    = (known after apply)
      + location_name    = (known after apply)
      + location_uuid    = (known after apply)
      + name             = "TXN-k8s-network"
      + network_type     = (known after apply)
      + status           = (known after apply)

      + timeouts {
          + create = "10m"
        }
    }

```
Also, this is the same case in both resources ipv4 and ipv6. There is no uuid argument reference to id. Also, verify other resources and update the documentation.

Please do correct this.

BR,
tmallikarjuna

**Comment by nvthongswansea** [comment]
@tmallikarjuna Thanks for pointing out these documentation errors. They should be fixed in the next release. Btw, if you want to use the public network (connect a server instance to the internet), please take a look at [gridscale public network](https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/data-sources/publicnetwork).

**Comment by nvthongswansea** [comment]
Close since the doc has been fixed.
