### ISSUE TITLE
gridscale_paas resource behavior will be changed

### ISSUE THREAD

**Issue by itakouna** [gridscale/terraform-provider-gridscale#104]
### Terraform Version
it's independent of Terraform Version

### Affected Resource(s)
- gridscale_paas

gridscale_paas resource behavior mainly for k8s will be changed. `k8s_version` will not be needed anymore, where the `service_template_uuid` specifies the intended k8s version.

### Current Terraform Configuration Files
```terraform
resource "gridscale_paas" "product_platform" {
  name                  = "test-k8s"
  service_template_uuid = "2471c07f-10f9-4d3f-bd30-9837ff4b6641"

  labels = ["test"]

  parameter {
    param = "k8s_version"
    type  = "string"
    value = "1.16.4-gs3"
  }

  parameter {
    param = "k8s_worker_node_ram"
    type  = "int"
    value = 2
  }

  parameter {
    param = "k8s_worker_node_cores"
    type  = "int"
    value = 1
  }

  parameter {
    param = "k8s_worker_node_count"
    type  = "int"
    value = 1
  }

  parameter {
    param = "k8s_worker_node_storage"
    type  = "int"
    value = 30
  }

  parameter {
    param = "k8s_worker_node_storage_type"
    type  = "string"
    value = "storage"
  }
}
```

### Expected Terraform Configuration Files
```terraform
# Copy-paste your Terraform configurations here - for large Terraform configs,
resource "gridscale_paas" "product_platform" {
  name                  = "test-k8s"
  service_template_uuid = "2471c07f-10f9-4d3f-bd30-9837ff4b6641"

  labels = ["test"]

  parameter {
    param = "k8s_worker_node_ram"
    type  = "int"
    value = 2
  }

  parameter {
    param = "k8s_worker_node_cores"
    type  = "int"
    value = 1
  }

  parameter {
    param = "k8s_worker_node_count"
    type  = "int"
    value = 1
  }

  parameter {
    param = "k8s_worker_node_storage"
    type  = "int"
    value = 30
  }

  parameter {
    param = "k8s_worker_node_storage_type"
    type  = "string"
    value = "storage"
  }
}
```

**Comment by itakouna** [comment]
@begotxe will add more details.

**Comment by bkircher** [comment]
Thanks. Any time frame on this?

**Comment by nvthongswansea** [comment]
Is it an issue? The parameters are not fixed. So you can add more of them or remove any of them, etc.

**Comment by begotxe** [comment]
there will be two changes introduced, as described by Ibrahim.

The first change:  The parameter 'k8s_version' will not be needed anymore, neither in the ADD/paas_service nor PATCH/paas_service. (The version will be provided by the service_template_uuid.)

The second change is that in PATCH/paas_service, the paas_service_uuid can be provided as an optional parameter.

**Comment by itakouna** [comment]
@nvthongswansea NIce! if we do not hard check on the parameters, we can say that our changes will not impact TF provider behavior.

**Comment by nvthongswansea** [comment]
I'll close this issue ticket since the changes does not affect the behaviour of gs TF provider.
