### ISSUE TITLE
Incompatibility with newer versions of Terraform

### ISSUE THREAD

**Issue by sharkwouter** [gridscale/terraform-provider-gridscale#11]
Hi there,
When trying to use the gridscale provider with the latest version of terraform I see an error message telling me the provider is not compatible with my version:
```
wouterwijsman@XPS13:~/Sources/gridscale-terraform-test$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No available provider "gridscale" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.


Error: no available version is compatible with this version of Terraform

```

### Terraform Version
Terraform v0.12.10

### Affected Resource(s)
The provider doesn't load.

### Terraform Configuration Files
```hcl
provider "gridscale" {
}
resource "gridscale_server" "terraform-test" {
	name ="terraform-test"
	cores = 1
	memory = 1
	power = true
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Run `terraform init` on the supplied configuration with the latest Terraform version available on the Terraform website.

### References
I've found some documentation about this issue on the Terraform wiki: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

**Comment by nvthongswansea** [comment]
@sharkwouter Thanks for reporting the issue. We'll take a look.

**Comment by bkircher** [comment]
@nvthongswansea  is this issue already resolved?

I can load current provider with Terraform v0.12.17.

**Comment by sharkwouter** [comment]
It has been fixed, so I'll close this issue.

**Comment by bkircher** [comment]
Thanks!
