### ISSUE TITLE
Cannot create sshkey when key is read from file

### ISSUE THREAD

**Issue by envy** [gridscale/terraform-provider-gridscale#112]
### Terraform Version
v0.14.4 (but 0.13.4 also affected)

### Affected Resource(s)
- sshkey

I have not tested other resources

### Terraform Configuration Files
```terraform
terraform {
  required_providers {
    gridscale = {
      source = "gridscale/gridscale"
      version = "1.8.0"
    }
  }
}

provider "gridscale" {
        uuid = "redacted"
        token = "redacted"
}

resource "gridscale_sshkey" "default" {
  name   = "default"
  sshkey = file("/path/to/id_rsa.pub")
}
```

### Debug Output
https://gist.github.com/envy/990e2b8ecccd43bd6619cdee479b0f7e

I redacted my UUID and token

### Panic Output
Did not panic.

### Expected Behavior
SSH key gets created successfully

### Actual Behavior
`Error: Status code: 400. Error: {'type': 'HTTPError', 'status_code': 400, 'message': "(400, 'Invalid letter in comment section')"}. Request UUID: ddc4ecac-1990-41a1-adc8-f1b85fd7726b.`

### Steps to Reproduce
1. Create a resource that reads an sshkey from a pub key file.
2. `terraform apply`

### Important Factoids
None

### References
None

**Comment by nvthongswansea** [comment]
Thanks for reporting. I will look into it.

**Comment by nvthongswansea** [comment]
@envy as far as I know, the `file` function will read a text file in this form. The `EOT` parts should not be a part of a public key.
![image](https://user-images.githubusercontent.com/9968099/105043685-1aef8180-5a66-11eb-8d6b-28c230aafa4c.png)

**Comment by envy** [comment]
True, but they aren't part of the keyfile, they are added by Terraform. I'm using the same construct for building a key pair with the AWS provider without problems:

```hcl
resource "aws_key_pair" "default" {
  key_name   = "default"
  public_key = file("/path/to/id_rsa.pub")
}
```

I prefer not to hardcode the public key into the terraform file.

Also, I don't think this is the issue, as this is valid terraform syntax for multiline strings: https://www.terraform.io/docs/configuration/expressions/strings.html#indented-heredocs

**Comment by envy** [comment]
Shot in the dark, but could the issue be the trailing newline here: https://gist.github.com/envy/990e2b8ecccd43bd6619cdee479b0f7e#file-gistfile1-txt-L653

The newline is not present in the file but added by terraform.

**Comment by nvthongswansea** [comment]
@envy Thanks for pointing that out.

**Comment by nvthongswansea** [comment]
@envy the problem should be fixed in the next release (I've opened a PR #113 )

**Comment by nvthongswansea** [comment]
@envy Hi! the version 1.8.1 of our tf provider has been released [v1.8.1](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.8.1). Could you check if your issue still presents?

**Comment by lachnerd** [comment]
Hi, i had a similiar, if not exactly the same problem, setting the sshkey with a variable.
I just checked it - works as expected now with v 1.8.1 - thx

**Comment by envy** [comment]
Yep, works now, thanks!
