### ISSUE TITLE
Unable to Spin Kubernetes PaaS Service.

### ISSUE THREAD

**Issue by tmallikarjuna** [gridscale/terraform-provider-gridscale#114]
Hi there,

Terraform version: 
Terraform v0.13.5
+ provider registry.terraform.io/gridscale/gridscale v1.8.0

I am not able to spawn k8s PaaS service on Gridscale with the same code I used on v1.7.3 of provider before a month.

I am missing with the parameter types of it.

Please do find the below output and really don't know where else I have to look for the parameter types apart from https://api.gridscale.io/objects/paas/services

Please do find the below output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.k8s_paas_service.gridscale_paas.paas will be created
  + resource "gridscale_paas" "paas" {
      + change_time           = (known after apply)
      + create_time           = (known after apply)
      + current_price         = (known after apply)
      + id                    = (known after apply)
      + labels                = [
          + "Cluster",
          + "Dev",
          + "TXN-Kubernetes",
          + "TXN-Services",
          + "k8s",
        ]
      + listen_port           = (known after apply)
      + name                  = "TXN-Kubernetes-Cluster"
      + network_uuid          = (known after apply)
      + password              = (known after apply)
      + security_zone_uuid    = (known after apply)
      + service_template_uuid = "22e93afb-6b9d-4524-98a4-6580169f76b1"
      + status                = (known after apply)
      + usage_in_minute       = (known after apply)
      + username              = (known after apply)

      + parameter {
          + param = "k8s_version"
          + type  = "string"
          + value = "1.19.4-gs1"
        }
      + parameter {
          + param = "k8s_worker_node_cores"
          + type  = "int"
          + value = "2"
        }
      + parameter {
          + param = "k8s_worker_node_count"
          + type  = "int"
          + value = "1"
        }
      + parameter {
          + param = "k8s_worker_node_ram"
          + type  = "int"
          + value = "2"
        }
      + parameter {
          + param = "k8s_worker_node_storage"
          + type  = "int"
          + value = "30"
        }
      + parameter {
          + param = "k8s_worker_node_storage_type"
          + type  = "string"
          + value = "storage"
        }

      + timeouts {
          + create = "10m"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + name     = "TXN-Kubernetes-Cluster"
  + password = (known after apply)
  + username = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.k8s_paas_service.gridscale_paas.paas: Creating...

Error: Status code: 400. Error: {'type': 'HTTPError', 'status_code': 400, 'message': "(400, 'Service parameters are not valid - please check the parameter schema definition')"}. Request UUID: b4e4207f-a8f7-4041-813b-dced4ec64dd6. 

```

**Comment by bkircher** [comment]
Yep, that's definitely a bug on our side. Can repro with 

```hcl
terraform {
  required_providers {
    gridscale = {
      source  = "gridscale/gridscale"
      version = "~> 1.8.0"
    }
  }
}

resource "gridscale_paas" "cluster" {
  name                  = "mycluster"
  # Kubernetes (Gen 1) 1.19.4-gs1
  service_template_uuid = "22e93afb-6b9d-4524-98a4-6580169f76b1"
  timeouts {
    create = "20m"
  }
}
```

Also produces a Bad Request.

```
Error: Status code: 400. Error: {'type': 'HTTPError', 'status_code': 400, 'message': "(400, 'Parameter k8s_worker_node_storage is required')"}. Request UUID: dba13f46-9f2a-4218-b291-6728ae99a457. 
```

**Comment by nvthongswansea** [comment]
> Yep, that's definitely a bug on our side. Can repro with
> 
> ```terraform
> terraform {
>   required_providers {
>     gridscale = {
>       source  = "gridscale/gridscale"
>       version = "~> 1.8.0"
>     }
>   }
> }
> 
> resource "gridscale_paas" "cluster" {
>   name                  = "mycluster"
>   # Kubernetes (Gen 1) 1.19.4-gs1
>   service_template_uuid = "22e93afb-6b9d-4524-98a4-6580169f76b1"
>   timeouts {
>     create = "20m"
>   }
> }
> ```
> 
> Also produces a Bad Request.
> 
> ```
> Error: Status code: 400. Error: {'type': 'HTTPError', 'status_code': 400, 'message': "(400, 'Parameter k8s_worker_node_storage is required')"}. Request UUID: dba13f46-9f2a-4218-b291-6728ae99a457. 
> ```

It said you forgot to add required parameters.

**Comment by nvthongswansea** [comment]
@bkircher Based on configuration of the tf file written by @tmallikarjuna, the parameter `k8s_version` is no longer valid, as far as I know. Because the version is attached to the `paas_service_template_uuid`. I removed that param, and it worked. Here is my config:
```
resource "gridscale_paas" "cluster" {
  name                  = "mycluster"
  service_template_uuid = "22e93afb-6b9d-4524-98a4-6580169f76b1"
  parameter {
	  param = "k8s_worker_node_cores"
	  type  = "int"
	  value = "2"
	}
  parameter {
	  param = "k8s_worker_node_count"
	  type  = "int"
	  value = "1"
	}
  parameter {
	  param = "k8s_worker_node_ram"
	  type  = "int"
	  value = "2"
	}
  parameter {
	  param = "k8s_worker_node_storage"
	  type  = "int"
	  value = "30"
	}
  parameter {
	  param = "k8s_worker_node_storage_type"
	  type  = "string"
	  value = "storage"
	}
  timeouts {
    create = "20m"
  }
}
```

**Comment by bkircher** [comment]
> It said you forgot to add required parameters.

Yeah. As we discussed offline, maybe it is time to rethink how we offer PaaS services here. In my opinion, Terraform should never (or very seldomly) provoke Bad Request from our API.

Maybe we should add new resources for individual PaaS services in the long run. TF should make it hard for me to do something wrong. And if I do, it should tell me already in the planning phase, if possible.

@tmallikarjuna does the example above help you with your problem?

**Comment by tmallikarjuna** [comment]
@bkircher I have not tested and will get back to you and really looking forward for this to work and excited to see faster response from you people. Appreciate it!!!.

**Comment by tmallikarjuna** [comment]
@bkircher I am able to deploy and unable to destroy
 Error: delete paas (8ae13b6b-a34d-4d53-a761-a15d12fae4de) resource - error: Status code: 426. Error: Deletion of platform services is currently not available for your client due to an issue in the terraform provider. A fix to the terraform provider will be provided shortly. Until then, platform services can still be removed in your panel. Sorry for the inconvenience.. Request UUID: dad770f8-8424-4ec0-b8b1-f0b74491420e.

**Comment by nvthongswansea** [comment]
@tmallikarjuna due to a change in API, we blocks all paas deletion requests from gridscale teraform provider <= v1.8.0. Please use >= v1.8.1 to delete your paas.

**Comment by tmallikarjuna** [comment]
Thanks it works :) but still please do update your documentation and keep updating somewhere where we can follow.

**Comment by bkircher** [comment]
Coolio. @nvthongswansea and me already have a couple of ideas on how to improve the whole PaaS Terraform story. We'll check back with the PaaS team first and than write something up [here](https://github.com/gridscale/terraform-provider-gridscale/issues/).
