### ISSUE TITLE
Reducing cores / memory does not cause server shutdown

### ISSUE THREAD

**Issue by MarcHarriss** [gridscale/terraform-provider-gridscale#12]
Hi, I am having trouble reducing the amount of cores I have on a server.

I have downloaded and compiled the gridscale provider myself, so I could potentially add some debug messages.
Terraform Version

Terraform v0.12.9
+ provider.gridscale (unversioned)

Affected Resource(s)

Please list the resources as a list, for example:

    gridscale_server

Terraform Configuration Files

resource "gridscale_server" "terraform-test" {
	name ="terraform-test"
	cores = 1
	memory = 1
	power = true
}

Output

Error: [Error] statuscode 500 returned: no error message received from server

on test.tf line 8, in resource "gridscale_server" "terraform-test":
8: resource "gridscale_server" "terraform-test" {
Expected Behavior

Server should shut down, update and restart
Actual Behavior

Server is still online, unchanged
Steps to Reproduce

    Create Server with 2 Cores via Terraform
    Change hcl file to only 1 core
    Rerun terraform apply

### References
Issue initially reported by  [@FabianTe](https://github.com/FabianTe) 
Moved this issue from [gridscales mirror repo](https://github.com/gridscale/terraform-provider-gridscale/issues/22) to have everything in one place

**Comment by MarcHarriss** [comment]
This issue should be fixed when we update the providers dependency to V2 of our gsclient-go. @itakouna @nvthongswansea  let's reference this issue as fixed along with that pull request.

**Comment by nvthongswansea** [comment]
This error disappears in PR https://github.com/terraform-providers/terraform-provider-gridscale/pull/15

**Comment by itakouna** [comment]
@FabianTe the issue has been solved in release v1.3.0

**Comment by fabiante** [comment]
Thank you!
