### ISSUE TITLE
Unable to destroy/Provision GSK PaaS 

### ISSUE THREAD

**Issue by tmallikarjuna** [gridscale/terraform-provider-gridscale#122]
Hi there,

PaaS security zone does not get destroyed after we destroy GKS Cluster.

When we try to provision GKS cluster again in the same project, it keeps failing. Also after deleting manually, I failed to provision GKS cluster.

I am fixing up a entire project with GKS and required resources to deploy similar environments and hence I am trying to provision and de-provision environment.

This is really becoming a nightmare for me and addition and deletion of any resource should go fine.

Please do fix this.

No even in the new project it is the same. Now, I am not able to spin up a GKS cluster at all :( 

```
module.k8s_paas_service.gridscale_paas.paas: Still creating... [7m50s elapsed]

Error: request 056d2d24-adab-476b-afc5-ad73e157ba52 failed with error Failure.

  on modules/k8s/main.tf line 1, in resource "gridscale_paas" "paas":
   1: resource "gridscale_paas" "paas" {


```
IT fails with above error and all resources get cleared by itself. 

Best Regards,
Tejesh

**Comment by bkircher** [comment]
Hey there. Let me check this with the back-end folks.

Do you have a bit of relevant HCL to repro for me?

>  de-provision environment

Just in case this helps, what I usually do for testing is using a dedicated project and when I'm done I just delete the entire project. This way i make sure to delete everything.

**Comment by tmallikarjuna** [comment]
@bkircher I have deleted the project and also tried reproducing in new project and still it fails.

**Comment by tmallikarjuna** [comment]
@bkircher It worked after 2 tries  and also after changing the project name!!!.  now I am able to proviison GKS cluster successfully.

**Comment by tmallikarjuna** [comment]
@bkircher Also, I wanted to know is it common that after successful destroy of the GKS cluster, does the PaaS Security Zone still remain in the project?. I destroyed it completely and the security zone is not getting destroyed.

**Comment by nvthongswansea** [comment]
@tmallikarjuna When you **just** create a PaaS service via terraform, a security zone will be automatically created. So that you will have to remove it manually. But if you create a security zone resource and a PaaS service, then link them via terraform. You can remove both of them by using just terraform.

**Comment by tmallikarjuna** [comment]
@nvthongswansea correct and if you don't link via terraform and if I do not delete Security zone, why kubernetes provisioning should fail?. I tried to respawn same environment. But, it still fails to provision and this is what I learnt from morning or maybe there might be an issue with the APIs.

**Comment by nvthongswansea** [comment]
@tmallikarjuna yep. The issue is from the backend. @bkircher already reported the issue to our backend team. Hopefully, we will get an answer soon.

**Comment by nvthongswansea** [comment]
@tmallikarjuna We've checked the log of the request. The issue doesn't relate to the security zone, it was just caused by our backend. And the issue is currently being handled by the team.

**Comment by nvthongswansea** [comment]
@tmallikarjuna does this issue still happen to you? If it does not, could you close this issue, please? Thanks!

**Comment by bkircher** [comment]
Closing. Feel free to re-open if there is anything left to do here.
