### ISSUE TITLE
Switch to 1.16 and enable macOS arm64 support again

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/terraform-provider-gridscale#129]
It fails, because gridscale terraform provider currently uses golang v1.13 which doesn't support macOS on Apple Silicon. This can be fixed by updating the version of golang to v1.16+

**Comment by bkircher** [comment]
FYI, https://hashicorp.slack.com/archives/C0HSE5WMB/p1613590067114200

**Comment by bkircher** [comment]
We also need to disable 32-bit again, got accidentally added in aebe106.
