### ISSUE TITLE
Terraform destroy raises error when instances powered up

### ISSUE THREAD

**Issue by MarcHarriss** [gridscale/terraform-provider-gridscale#13]
A terraform destroy (or any other action where a server resource is destroyed) will currently error out on part of the API if server instances are powered up. The expected behavior would be for the provider to power down instances implicitly so that the requested or planned resource destruction goes through.

### References
Duplicate issue [here](https://github.com/gridscale/terraform-provider-gridscale/issues/13), as that repo will be archived 
originally reported by @eigengrau

**Comment by nvthongswansea** [comment]
Server instances are now stopped before getting deleted. PR https://github.com/terraform-providers/terraform-provider-gridscale/pull/15

**Comment by itakouna** [comment]
@eigengrau The issue has been solved in release v1.3.0
