### ISSUE TITLE
Suggestion for new MS SQL Server resource

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/terraform-provider-gridscale#136]
Similar to #120, this suggestion is for new SQL server tf resource. The schema proposal will be provider later.

**Comment by bkircher** [comment]
Example here: https://github.com/gridscale/terraform-examples/tree/master/ms-sql-server

**Comment by bkircher** [comment]
@nvthongswansea 

Looks good so far! Let's make the resource name `"gridscale_sqlserver"` instead of what we have now though. This is closer to the actual Microsoft product name and more distinguishable from `"gridscale_mysql"` resource.
