### ISSUE TITLE
Support firewall configuration

### ISSUE THREAD

**Issue by MarcHarriss** [gridscale/terraform-provider-gridscale#14]
Currently, there is no support to provision firewall templates or to attach firewall rules and templates to instances.

### References
Issue initially reported by @eigengrau [here](https://github.com/gridscale/terraform-provider-gridscale/issues/11), moved because that repo will be archived.

**Comment by nvthongswansea** [comment]
Done in PR https://github.com/terraform-providers/terraform-provider-gridscale/pull/25
