### ISSUE TITLE
The ordering of network in server resource always asks for update (mult. networks attached to one server)

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/terraform-provider-gridscale#142]
Even though nothing is changed in a server resource, the ordering of the network always ask for update (when mult. networks attached to one server). This is not good, since updating network in a server resource requires the server to be off.

**Comment by bkircher** [comment]
Re-open because this is a breaking change

**Comment by bkircher** [comment]
If it is okay with you @nvthongswansea , I will move  3857fd8  to a separate branch (named v2 or so) and revert this commit in master?

**Comment by nvthongswansea** [comment]
> If it is okay with you @nvthongswansea , I will move [3857fd8](https://github.com/gridscale/terraform-provider-gridscale/commit/3857fd8f1318e86cd02e30823d9e5cf48a8e1823) to a separate branch (named v2 or so) and revert this commit in master?

Give me a few hours, I might find something that can fix the back-compat.

**Comment by nvthongswansea** [comment]
@bkircher could you rollback the master branch and move the [3857fd8](https://github.com/gridscale/terraform-provider-gridscale/commit/3857fd8f1318e86cd02e30823d9e5cf48a8e1823) to a separate branch, please?

**Comment by nvthongswansea** [comment]
Or you can remove that completely, since I found other way to deal with the network ordering issue.

**Comment by bkircher** [comment]
Reverted on master. We can create a new branch (v2) as target branch for changes that are backward incompatible and need a major version bump.

**Comment by nvthongswansea** [comment]
Done in [v1.14.0](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.14.0).
