### ISSUE TITLE
Upgrade `terraform-plugin-sdk` package

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/terraform-provider-gridscale#146]
Since `terraform-plugin-sdk v2` has been released for a while. There are a lot of improvements and changes in the latest version of `terraform-plugin-sdk`. I think we shoud switch to  `terraform-plugin-sdk v2` in the next major release of `terraform-provider-gridscale`.

**Comment by bkircher** [comment]
Hey, are you sure this is a breaking change? Changes here should only be internal to provider implementation, right? Not in user-visible behavior

**Comment by nvthongswansea** [comment]
Link to [Terraform Plugin SDK v2 Upgrade Guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html)

**Comment by bkircher** [comment]
Removed breaking change label. This should not result in any user visible changes or changes in behavior. Still needs to be double checked.

**Comment by bkircher** [comment]
Thanks @nvthongswansea 

Do we need to do something about our use of `acctest` package? Not sure I understand https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#removal-of-the-acctest-package

**Comment by nvthongswansea** [comment]
@bkircher nah. It doesn't affect our current acctest.
