### ISSUE TITLE
New k8s resource: upgrading the release not working

### ISSUE THREAD

**Issue by bkircher** [gridscale/terraform-provider-gridscale#149]
TF upgrade from, i.e., 1.17 → 1.18 is not working yet.

PATCH on the {"service_template_uuid":"8822aee2-cdfb-4278-a62b-16f6eee0a3ce"} seems to be too "quick". A second `terraform apply` won't work because the local TF state has already changed.

**Comment by nvthongswansea** [comment]
@bkircher @itakouna I've realized that the [docs of PaaS PATCH](https://gridscale.io/en/api-documentation/index.html#operation/updatePaasService) is not correct, the field `paas_service_template_uuid` should be `service_template_uuid`. The gsclient-go uses  `paas_service_template_uuid` which causes the issue. BTW, I think this is also a inconsistency issue.  In [the PaaS POST's docs](https://gridscale.io/en/api-documentation/index.html#operation/createPaasService), the field is `paas_service_template_uuid`, while the PaaS Update uses `service_template_uuid` (which is also different from what [the PaaS PATCH's docs](https://gridscale.io/en/api-documentation/index.html#operation/updatePaasService) states).
![image](https://user-images.githubusercontent.com/9968099/114176933-14252c00-993c-11eb-9dd6-c40b4b290e01.png)

**Comment by nvthongswansea** [comment]
> @bkircher @itakouna I've realized that the [docs of PaaS PATCH](https://gridscale.io/en/api-documentation/index.html#operation/updatePaasService) is not correct, the field `paas_service_template_uuid` should be `service_template_uuid`. The gsclient-go uses `paas_service_template_uuid` which causes the issue. BTW, I think this is also a inconsistency issue. In [the PaaS POST's docs](https://gridscale.io/en/api-documentation/index.html#operation/createPaasService), the field is `paas_service_template_uuid`, while the PaaS Update uses `service_template_uuid` (which is also different from what [the PaaS PATCH's docs](https://gridscale.io/en/api-documentation/index.html#operation/updatePaasService) states).
> ![image](https://user-images.githubusercontent.com/9968099/114176933-14252c00-993c-11eb-9dd6-c40b4b290e01.png)

This issue also relates to #151

**Comment by itakouna** [comment]
@nvthongswansea would you test with `service_template_uuid`? I've already created a ticket to update the API spec.

**Comment by nvthongswansea** [comment]
@itakouna just tested, it works with `service_template_uuid`. I prefer `paas_service_template_uuid` since it is stated in [the docs of PaaS PATCH](https://gridscale.io/en/api-documentation/index.html#operation/updatePaasService), and it is consistent with the PaaS POST's schema.

**Comment by nvthongswansea** [comment]
@bkircher @itakouna So will it be fixed in the backend side or gsclient-go side?

**Comment by nvthongswansea** [comment]
Fixed with [gsclient-go v3.6.1](https://github.com/gridscale/gsclient-go/releases/tag/v3.6.1).
