### ISSUE TITLE
New postgresql resource: patch performance_class needs debugging

### ISSUE THREAD

**Issue by bkircher** [gridscale/terraform-provider-gridscale#151]
Creating the new resource looks awesome. Changing individual properties still has rough edges, i.e. setting `performace_class` from insane → ultra returns way too quickly... and actually does not change. TF state changes nonetheless leaving it broken. Needs a bit of debugging.

**Comment by nvthongswansea** [comment]
This issue relates to #149

**Comment by nvthongswansea** [comment]
Fixed with [gsclient-go v3.6.1](https://github.com/gridscale/gsclient-go/releases/tag/v3.6.1).
