### ISSUE TITLE
Support for fixing DHCP IPs?

### ISSUE THREAD

**Issue by fabiante** [gridscale/terraform-provider-gridscale#186]
Hi there,

I am happily using the DHCP feature of the internal networks and while doing so, I noticed, that statically asigning ip ranges is not supported via terraform, as it is in the UI:

![grafik](https://user-images.githubusercontent.com/7669818/142181649-a900c17c-4843-4a5d-b932-80fcbfcb73b9.png)

This would be a great addition.

**Comment by nvthongswansea** [comment]
@FabianTe Thank you! We will consider it.

**Comment by nvthongswansea** [comment]
Added DHCP IP manual assignment in [v1.14.0](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.14.0).

**Comment by nvthongswansea** [comment]
More info [DHCP IP assignment](https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/server#ip)
