### ISSUE TITLE
List of public templates

### ISSUE THREAD

**Issue by semtyre** [gridscale/terraform-provider-gridscale#201]
Hi there,

the [terraform help for gridscale provider states](https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/data-sources/template) that the list of public templates can be seen in the Expert Panel.
Since [UI overhaul](https://gridscale.io/en/blog/the-new-unified-cloud-panel/) the Expert Panel doesn't exist anymore, how can we check which templates are available?

### Affected Resource(s)
gridscale_template

### Terraform Configuration Files
```terraform
data "gridscale_template" "ubuntu" {
  name = "???"
}
```

Thanks!

**Comment by nvthongswansea** [comment]
@semtyre Hi, you can get the names of the templates via the tool [gscloud](https://github.com/gridscale/gscloud), or via API endpoint [getTemplates](https://gridscale.io/en//api-documentation/index.html#operation/getTemplates). For your convenience, this is a list of current templates' names:
```
AlmaLinux
Fedora 35
Rocky Linux
CentOS Stream 8
Debian 11
Windows Server 2022
Ubuntu 20.04 LTS (Focal Fossa)
Debian 10
Windows Server 2019
Ubuntu 18.04 LTS
CentOS 7 (x86_64)
Windows Server 2016 
```

**Comment by semtyre** [comment]
Thanks, @nvthongswansea !
