### ISSUE TITLE
How to link `gridscale_mariadb` to a private network?

### ISSUE THREAD

**Issue by semtyre** [gridscale/terraform-provider-gridscale#208]
Hi there,

in the cloud panel it is possible to link a managed mariadb service to a private network.
I think this is a rather recently added new feature.

The gridscale provider only allows linking to a security zone.
How can we link it to a private network instead (using terraform)?

Best regards,

**Comment by nvthongswansea** [comment]
@semtyre Hi, it will be possible to do so in the next release (PR #199 ).

**Comment by semtyre** [comment]
@nvthongswansea That are good news 👍 Do you know when the next version will be released?

**Comment by nvthongswansea** [comment]
@nvthongswansea It has been released https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.15.0
