### ISSUE TITLE
resource name of microsoft sql server is wrong in docs

### ISSUE THREAD

**Issue by SBejga** [gridscale/terraform-provider-gridscale#213]
Hi there,

the documentation is wrong regarding resource of Microsoft SQL Server.

The documentation says, it is `resource "gridscale_mssql"`
see https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/mssql

But actually it is `resource "gridscale_sqlserver"`

I got the following error: 
```
 Error: Invalid resource type
│ 
│   on mssql.tf line 1, in resource "gridscale_mssql" "terra-sqlserver-test":
│    1: resource "gridscale_mssql" "terra-sqlserver-test" {
│ 
│ The provider gridscale/gridscale does not support resource type "gridscale_mssql". Did you mean "gridscale_mysql"?
```

and looked into the code:  https://github.com/gridscale/terraform-provider-gridscale/blob/9ff1a5ee4e6abcf89c0aae9a6e639e38b0d0b9c5/gridscale/provider.go#L97

**Comment by nvthongswansea** [comment]
@SBejga you are right. We forgot to update the docs for this resource. Thank you for reporting this issue.

**Comment by nvthongswansea** [comment]
@SBejga Hi, we have improved our documentation. The docs for `gridscale_sqlserver` is now [here](https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/sqlserver).
