### ISSUE TITLE
gridscale_object_storage_accesskey: add 'name' attribute

### ISSUE THREAD

**Issue by mbunkus** [gridscale/terraform-provider-gridscale#218]
### Terraform Version

```
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/gridscale/gridscale v1.17.0
```

### Affected Resource(s)

- gridscale_object_storage_accesskey

### Terraform Configuration Files

Works:

```terraform
resource "gridscale_object_storage_accesskey" "test" {
}
```

Doesn't work:

```terraform
resource "gridscale_object_storage_accesskey" "test" {
  name = "test"
}
```

Neither does this:

```terraform
resource "gridscale_object_storage_accesskey" "test" {
  comment = "test"
}
```

### Expected Behavior

I'd very much like to be able to name my access keys. Otherwise they all show up as `[Unnamed]` in the web UI, making telling them apart really difficult. The [API](https://my.gridscale.io/APIDoc#tag/object-storage/operation/updateAccessKey) does allow specifying a comment.

### Actual Behavior

Terraform complains that the argument `name` isn't expected here.

**Comment by nvthongswansea** [comment]
a new version [v1.19.0](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.19.0) has been released.
