### ISSUE TITLE
Reducing cores / memory does not cause server shutdown

### ISSUE THREAD

**Issue by FabianTe** [gridscale/terraform-provider-gridscale#22]
Hi, I am having trouble reducing the amount of cores I have on a server.

I have downloaded and compiled the gridscale provider myself, so I could potentially add some debug messages.

### Terraform Version
```
Terraform v0.12.9
+ provider.gridscale (unversioned)
```

### Affected Resource(s)
Please list the resources as a list, for example:
- gridscale_server

### Terraform Configuration Files 
```hcl
resource "gridscale_server" "terraform-test" {
	name ="terraform-test"
	cores = 1
	memory = 1
	power = true
}
```

### Output
Error: [Error] statuscode 500 returned: no error message received from server

  on test.tf line 8, in resource "gridscale_server" "terraform-test":
   8: resource "gridscale_server" "terraform-test" {

### Expected Behavior
Server should shut down, update and restart

### Actual Behavior
Server is still online, unchanged

### Steps to Reproduce
1. Create Server with 2 Cores via Terraform
2. Change hcl file to only 1 core
3. Rerun `terraform apply`

**Comment by sharkwouter** [comment]
I did a little bit of testing and I got the following debug output when trying this:
```
2019-10-04T15:31:32.226+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.0.0_x4: 2019/10/04 15:31:32 [DEBUG] PATCH request sent to URL: https://api.gridscale.io/objects/servers/23672141-bf4c-45df-b3d4-9973cea29532/shutdown
2019-10-04T15:31:32.226+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.0.0_x4: 2019/10/04 15:31:32 [DEBUG] Request body: {null
2019-10-04T15:31:32.226+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.0.0_x4: }
2019-10-04T15:31:32.253+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.0.0_x4: 2019/10/04 15:31:32 [DEBUG] Status code returned: 500
2019/10/04 15:31:32 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error occurred:
	* gridscale_server.terraform-test: [Error] statuscode 500 returned: no error message received from server
```
It seems the issue could be that the go client is adding a body to the shutdown request containing the word "null". I'm guessing [this line](https://github.com/gridscale/gsclient-go/blob/2beb2fbf4a29555ef64480b599e78f6a514a1e27/server.go#L516) in the go-client is not needed and removing it could fix the issue, but I haven't verified this yet.

**Comment by sharkwouter** [comment]
> It seems the issue could be that the go client is adding a body to the shutdown request containing the word "null". I'm guessing [this line](https://github.com/gridscale/gsclient-go/blob/2beb2fbf4a29555ef64480b599e78f6a514a1e27/server.go#L516) in the go-client is not needed and removing it could fix the issue, but I haven't verified this yet.

I've just tried the change I suggested, which changes the error to a 400 error:
```
2019-10-04T16:09:36.104+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.2: 2019/10/04 16:09:36 [DEBUG] PATCH request sent to URL: https://api.gridscale.io/objects/servers/4d8cf395-d97f-4ccb-bdf2-fac44958132d/shutdown
2019-10-04T16:09:36.104+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.2: 2019/10/04 16:09:36 [DEBUG] Request body: {}
2019-10-04T16:09:36.127+0200 [DEBUG] plugin.terraform-provider-gridscale_v1.2: 2019/10/04 16:09:36 [DEBUG] Status code returned: 400
2019/10/04 16:09:36 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error occurred:
	* gridscale_server.terraform-test: [Error] statuscode 400 returned: no error message received from server
```
I hope this will help resolve this issue. Thanks for reporting it

**Comment by nvthongswansea** [comment]
@FabianTe @sharkwouter Hi, this repo is not official (as terraform provider is under terraform's control). The official one is https://github.com/terraform-providers/terraform-provider-gridscale

**Comment by FabianTe** [comment]
Sooo, this repo is only a mirror?

How to approach this now? Shall I or @sharkwouter (thanks for the help) create a PR there?

**Comment by nvthongswansea** [comment]
> Sooo, this repo is only a mirror?
> 
> How to approach this now? Shall I or @sharkwouter (thanks for the help) create a PR there?

Yes, please create PRs on the official repo.

**Comment by itakouna** [comment]
@nvthongswansea this issue should be solved after upgrading the gsclient-go to v2.0.0

**Comment by FabianTe** [comment]
Is someone already working on updating the gcclient-go dependency to v2?

Wouldn't want to do redundant work.

**Comment by MarcHarriss** [comment]
Hi @FabianTe, we're currently working on updating the providers gsclient-go dependency to v2. You can track our progress [here](https://github.com/terraform-providers/terraform-provider-gridscale/issues/12), as this is the official repository - I duplicated the ticket there (I will be archiving this one). We will open a pull request on the official repository once ready, further updates can be found there.
