### ISSUE TITLE
missing darwin_arm64 package for v1.18.0

### ISSUE THREAD

**Issue by luy-infrastructure** [gridscale/terraform-provider-gridscale#226]
terraform provider v1.18.0 currently won't work with arm mac.

### Terraform Version
Terraform v1.3.9

### Terraform Configuration Files
```terraform
       gridscale = {
            source = "gridscale/gridscale"
            version = "1.18.0"
        }
```

### Debug Output
https://gist.github.com/luy-infrastructure/1d2a7ae6724f4e538630e14a03243de5

### Expected Behavior
Should work on all platforms.

### Actual Behavior
Doesn't work on darwin_arm64.

### Steps to Reproduce
1. `terraform init`

**Comment by nvthongswansea** [comment]
@luy-infrastructure thank you for reporting this issue. For some reasons, the github action workflow skipped `darwin/arm64 build` and `windows/arm64 build`. I will take a look.

**Comment by nvthongswansea** [comment]
@luy-infrastructure I've made a new release [v1.18.1](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.18.1) which also includes the missing builds.
