### ISSUE TITLE
docs: wrong name for gridscale_object_storage_bucket in menu

### ISSUE THREAD

**Issue by mbunkus** [gridscale/terraform-provider-gridscale#227]
Over on the [Terraform docs page](https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/bucket) the menu entry on the right contains `gridscale_bucket`, whereas the module itself is called `gridscale_object_storage_bucket`. The heading on that page is correct, though.

**Comment by nvthongswansea** [comment]
@mbunkus a new version [v1.19.0](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.19.0) has been released.
