### ISSUE TITLE
Kubeconfig as Kubernetes ressource argument

### ISSUE THREAD

**Issue by FloSchick** [gridscale/terraform-provider-gridscale#228]
It would be nice to be able to retrieve the kubeconfig for a managed k8s cluster directly as terraform output.
Other providers have implemented this such as azure: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kube_admin_config

Currently we must use scripts wich access the API or use the gscloud binary every time some automated terraform tools like ci/cd apply changes to. the cluster.

**Comment by nvthongswansea** [comment]
@FloSchick There is an attribute called `kubeconfig` in the resource `gridscale_k8s` for your usecase. This attribute is missing from gridscale terraform provider document, therefore, I will update the docs.

**Comment by FloSchick** [comment]
@nvthongswansea Thank you for that hint. I tested it and unfortunately it looks like the kubeconfig which is stored in the state is not refreshed when planning or applying with terraform. Therefore, when using this kubeconfig for authentication for other terraform providers such as helm, it does not work anymore after three days when the kubeconfig expires.

I would expect, that the kubeconfig in state is refreshed when running terraform plan or apply commands.

**Comment by nvthongswansea** [comment]
@FloSchick thank you. We will solve this issue in the next release.

**Comment by SBejga** [comment]
One additional question, would it be possible to mark the `kubeconfig` property as computed?
Currently, terraform will warn after the expiration:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.cluster.gridscale_k8s.cluster has changed
~ resource "gridscale_k8s" "cluster" {
        id                       = "xxxxxxxxxx"
      ~ kubeconfig               = (sensitive value)
        name                     = "xxxxxxxxxxx"
        # (9 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
```

We tried to ignore that change with:
```
lifecycle {
    ignore_changes = [
      kubeconfig,
    ]
  }
```

But this does not work: 

> Adding an attribute name to ignore_changes tells Terraform to ignore future│ changes to the argument in configuration after the object has been created,│ retaining the value originally configured.│ │ The attribute kubeconfig is decided by the provider alone and therefore│ there can be no configured value to compare with. Including this attribute│ in ignore_changes has no effect. Remove the attribute from ignore_changes│ to quiet this warning.

To silence the warnings about `Objects have changed outside of Terraform` will reduce confusion working with the cluster.

**Comment by nvthongswansea** [comment]
@SBejga it has been computed since the beginning. Tf also notifies when the computed fields are changed.

**Comment by nvthongswansea** [comment]
@SBejga @FloSchick a new version [v1.19.0](https://github.com/gridscale/terraform-provider-gridscale/releases/tag/v1.19.0) has been released.
