### ISSUE TITLE
gsk autoscaler not working properly with Terraform Provider

### ISSUE THREAD

**Issue by FloSchick** [gridscale/terraform-provider-gridscale#236]
Thanks for adding autoscaling capabilities to gsk, however the current implementation is not optimal when using it with the terraform provider. After successful upscaling, the tf-provider wants to delete that node an the next apply run. 

The only viable solution to this is adding `ignore_changes` to the cluster:

```
lifecycle {
    ignore_changes = [ node_pool.0.node_count]
  }
```
This is also not optimal as you lose the ability to manually increase node size with terraform.
Are there any plans to integrate the autoscaling feature into the gsk platform and adding it to the terraform provider as variables of the cluster, as most providers implement it like that?

**Comment by nvthongswansea** [comment]
@FloSchick thank you for reporting this issue. We will look into it.
