### ISSUE TITLE
Cannot create redis instance with terraform

### ISSUE THREAD

**Issue by se2a** [gridscale/terraform-provider-gridscale#264]
Hi there,

We cannot create redis instance, no matter which performance class we would choose. Looks like property is being passed but rejected by provider.

### provider version
Provider: 
```
Latest Version -> Version 1.23.1
Published 2 days ago 
```

### Terraform Version
Terraform Version: 1.1.7

### Affected Resource(s)
- gridscale_redis_cache

### Terraform Configuration Files
```terraform
resource "gridscale_redis_cache" "redis" {
  name              = var.name
  release           = var.release
  performance_class = var.performance_class
  labels            = var.labels
  network_uuid      = var.network_uuid
}
```

### Expected Behavior
new redis instance should be created, according to:

https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/redis_cache

```terraform
resource "gridscale_redis_cache" "terra-redis-cache-test" {
  name = "test"
  release = "5.0"
  performance_class = "standard"
  labels = ["test"]
}
```

tfvars file:
```
redis_configs = {
  "general" = {
    release           = "7.0"
    performance_class = "high"
    labels            = ["redis"]
    k8s_cluster_key   = "general"
  }
}
```

### Actual Behavior
there is an error from terraform:

```terraform
│ Error: release 7.0 with performance class high is not a valid Redis cache release/performance class. Valid releases with corresponding performance classes are:
│ 	release 7 has following perfomance classes: ultra, insane, high, standard
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
It doesn't matter which performance_class we provide: ultra, insane, high or standard, the output is always the same.

**Comment by nvthongswansea** [comment]
Thanks for reporting. I will check it asap @se2a

**Comment by nvthongswansea** [comment]
@se2a I've found the issue. Since the release `7`, we decided to use the major release string only. So no more `7.0`, it is just `7`. I will update our terraform example for this change.

**Comment by se2a** [comment]
@nvthongswansea working now! thx for such quick help.
