### ISSUE TITLE
GSK 1.30 Enable Hubble Integration with Terraform

### ISSUE THREAD

**Issue by FloSchick** [gridscale/terraform-provider-gridscale#396]
With the release of GSK version 1.30, which now supports enabling the Hubble UI through the Gridscale Panel, this functionality should also be available in the Gridscale Terraform provider as part of the Cluster configuration parameters.

**Comment by nvthongswansea** [comment]
@FloSchick Thank you. We are adding new gsk parameters.

**Comment by nvthongswansea** [comment]
[PR](https://github.com/gridscale/terraform-provider-gridscale/pull/402) has been merged.
