### ISSUE TITLE
Minimal Working Example in Terraform Documentation for K8s Cluster Provisioning Fails with v1.30

### ISSUE THREAD

**Issue by FloSchick** [gridscale/terraform-provider-gridscale#401]
Hi there,

the minimal working example for provisioning a Kubernetes cluster from the Terraform documentation fails when using version 1.30. This seems related to the recent preview feature for node pools, but the example does not work as expected and throws an error during terraform apply.

```terraform
resource "gridscale_k8s" "k8s-test" {
  name   = "test"
  release = "1.30" # instead, gsk_version can be set.
  node_pool {
  name = "my_node_pool"
    node_count = 2
    cores = 1
    memory = 2
    storage = 10
    storage_type = "storage_insane"
    rocket_storage = 90
  }
 }
```

Running `terraform apply` results in the following error from the API:
```bash
Error: create k8s () resource - error: Status code: 400. Error: {'type': 'HTTPError', 'status_code': 400, 'message': "(400, 'Parameter pools is required')"}. Request UUID: 3c249774-85d3-4370-aa7e-3ceb93c721fc. 
│ 
│   with gridscale_k8s.k8s-test,
│   on main.tf line 1, in resource "gridscale_k8s" "k8s-test":
│    1: resource "gridscale_k8s" "k8s-test" {
│ 
```
**Observations:**

- The error message indicates that the pools parameter is required, which is confusing because it’s unclear how this should be configured with the provided node pool syntax.
- Additionally, the new node pool parameters, including node_pool configuration, are missing from the Terraform documentation, making it challenging to resolve this issue.

**Expected Behavior:** 
Please clarify the correct configuration for node pools in Terraform v1.30 and update the documentation accordingly.

**Comment by nvthongswansea** [comment]
@FloSchick Hi, there is a [PR #394](https://github.com/gridscale/terraform-provider-gridscale/pull/) for this and it was merged last week. We will make an official release of gridscale terraform provider v2 as soon as we remove the `lab` label from gsk 1.30 in gridscale panel.

**Comment by FloSchick** [comment]
@nvthongswansea Thanks for the fast reply! Any rough estimations when this will happen? Also, I´m missing the Hubble parameter from the docs mentioned in my previous issue https://github.com/gridscale/terraform-provider-gridscale/issues/396, seems like its missing in the PR as well. Could you double check?

**Comment by nvthongswansea** [comment]
@FloSchick I cannot give a concrete estimation yet. But I think we can release a beta version. Regarding the Hubble parameters, I will open PRs for that.

**Comment by FloSchick** [comment]
Thanks @nvthongswansea, a beta version would be great as we then can already do some testing with 1.30 and Terraform.

**Comment by nvthongswansea** [comment]
> Thanks @nvthongswansea, a beta version would be great as we then can already do some testing with 1.30 and Terraform.

After a discussion within our team, we decided not to release a version before the `lab` label removal. The problem is that if something goes wrong (mostly from API), we cannot assure the terraform state. At least until some critical API issues in our managed k8s cluster are fixed.

**Comment by FloSchick** [comment]
@nvthongswansea alright, thanks for the update. Will wait for the official release then.
