### ISSUE TITLE
Terraform Provider Development Program- Final Review

### ISSUE THREAD

**Issue by cgriggs01** [gridscale/terraform-provider-gridscale#5]
Hey Team,

Hope everyone is doing well. We have compile a few more items of feedback to finalize the provider and once completed, will be ready to merge and release the provider into the terraform-providers/ ecosystem. 

- [x] The datasource and resource filenames should include the provider name:
`datasource_ip.go` --> `datasounce_gridscale_ip.go`
 `resource_ipv4.go` --> `resource_gridscale_ipv4.go`

- [x] All complex fields of type; Set, Map, List must be error checked when d.Set() is called on it. This is seen in each resource for the `labels` field along with a few other fields. Any fields with a simple type; Int, Float, String, Bool, ect, should never be checked when d.Set() is called. 

- [x] In [resource_server.go](https://github.com/gridscale/terraform-provider-gridscale/blob/master/gridscale/resource_server.go#L174-L185) there are three fields which are commented out. If these are not going to be implemented they should be removed. 

- [x] All providers are now being build on >go1.11.5 and using Go Modules for managing the dependancies and populating the vendor/ directory. 

Please let me know if you have any other questions.

Best,
Chris

**Comment by fkr** [comment]
Hi Chris,

thanks for the feedback. We will address these issues shortly.

regards,

felix

**Comment by fkr** [comment]
#7

**Comment by fkr** [comment]
Hi Chris,

the issues you raised have been dealt with. Thanks for your time and feedback.
Am very much looking forward to the next steps.

regards & happy easter,

felix
