### ISSUE TITLE
Fix server examples in Docs

### ISSUE THREAD

**Issue by itakouna** [gridscale/terraform-provider-gridscale#54]
terraform-provider-gridscale v1.4 and up do not support setting bootdevice explicitly for storages.

https://github.com/terraform-providers/terraform-provider-gridscale/blob/master/website/docs/d/storage.html.md

https://github.com/terraform-providers/terraform-provider-gridscale/blob/master/website/docs/r/server.html.md

**Comment by nvthongswansea** [comment]
https://github.com/terraform-providers/terraform-provider-gridscale/pull/55

**Comment by itakouna** [comment]
#55
