### ISSUE TITLE
Documentation of resource "gridscale_paas" leads to security zone documentation

### ISSUE THREAD

**Issue by fabiante** [gridscale/terraform-provider-gridscale#57]
### Expected Behavior
Clicking on the navigation link for gridscale_paas on the [plugin documentation](https://www.terraform.io/docs/providers/gridscale/r/securityzone.html) should open the paas documentation.

### Actual Behavior
The documentation for gridscale_paas_securityzone is opened.

**Comment by fkr** [comment]
Thanks for the bug report as well as the fix! ✌️ 👍

**Comment by fabiante** [comment]
Your welcome!

Next PR might be something more interesting that "fix typo in readme" :muscle: :laughing:
