### ISSUE TITLE
How to connect a Server to the Public Network (Internet)?

### ISSUE THREAD

**Issue by fabiante** [gridscale/terraform-provider-gridscale#59]
I just noticed this in the documentation:

> ipv4 - (Optional) The UUID of the IPv4 address of the server. (***NOTE: The server will NOT automatically be connected to the public network; to give it access to the internet, please add server to the public network.)

Is there a way to automaticall connect a server resource to the internet? I tried declaring a network resource with the name "Public Network" but just created a private network.

**Comment by fabiante** [comment]
I tested a bit and found that when adding the public network manually and then running `terraform apply` it tries to remove the added network, which of course is a correct behaviour:

```
      - network {
          - bootdevice   = false -> null
          - create_time  = "2020-02-19 18:57:26 +0000 UTC" -> null
          - mac          = "2a:4f:8e:14:e4:01" -> null
          - network_type = "network" -> null
          - object_name  = "Public Network" -> null
          - object_uuid  = "4996c084-4bc2-47eb-95b4-53cfc34aee14" -> null
          - ordering     = 0 -> null
        }
```

I haven't yet tried, but could I take this `object_uuid` and use it? Feels kind of sketchy...

**Comment by nvthongswansea** [comment]
We have public network datasource for that 
`data "gridscale_public_network" "pubnet"{
}

resource "gridscale_server" "servername"{
	name = "terra-server"
	cores = 2
	memory = 4
	network {
		object_uuid = data.gridscale_public_network.pubnet.id
		bootdevice = true
	}
}`

**Comment by fabiante** [comment]
Oh thank you, didn't see that.
