### ISSUE TITLE
Creation of gridscale_paas Kubernetes resource timesout after 2mins 

### ISSUE THREAD

**Issue by benjackwhite** [gridscale/terraform-provider-gridscale#69]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- gridscale_paas

### Terraform Configuration Files
```terraform
resource "gridscale_paas" "product_platform" {
  name                  = "test-k8s"
  service_template_uuid = "2471c07f-10f9-4d3f-bd30-9837ff4b6641"

  labels = ["test"]

  parameter {
    param = "k8s_version"
    type  = "string"
    value = "1.16.4-gs3"
  }

  parameter {
    param = "k8s_worker_node_ram"
    type  = "int"
    value = 2
  }

  parameter {
    param = "k8s_worker_node_cores"
    type  = "int"
    value = 1
  }

  parameter {
    param = "k8s_worker_node_count"
    type  = "int"
    value = 1
  }

  parameter {
    param = "k8s_worker_node_storage"
    type  = "int"
    value = 30
  }

  parameter {
    param = "k8s_worker_node_storage_type"
    type  = "string"
    value = "storage"
  }
}
```

### Debug Output
-

### Expected Behavior
The provider should wait for a long enough period to allow the PaaS provisioning of Kubernetes to complete. In the Gridscale UI it takes somewhere between 5 and 15 mins to stabilise in a completed state.

### Actual Behavior
After 2 minutes terraform errors due to a timeout

### Steps to Reproduce
1. Setup Gridscale provider
2. Include referenced config above
3. `terraform apply`
4. Observe timeout after 2 minutes

### Important Factoids
After looking into the code this could be deeper as an issue with the Go client for Gridscale but I am not certain

**Comment by nvthongswansea** [comment]
Thanks for reporting this issue. I have opened a PR to solve this issue so far [https://github.com/terraform-providers/terraform-provider-gridscale/pull/70](url)

**Comment by bkircher** [comment]
Done with 1.5.1
