### ISSUE TITLE
Terraform doesn't automatically drop non-defined rules.

### ISSUE THREAD

**Issue by nvthongswansea** [gridscale/terraform-provider-gridscale#89]
Based on https://registry.terraform.io/providers/gridscale/gridscale/latest/docs/resources/firewall, the docs says "Packets that do not match any rules are blocked by default". However, the non-defined rules are not dropped automatically by Terraform.

**Comment by bkircher** [comment]
Docs updated in master branch.

**Comment by bkircher** [comment]
Will tackle this next week.

**Comment by bkircher** [comment]
Fixed with next release

**Comment by bkircher** [comment]
Done
