### ISSUE TITLE
Document FW changes more thoroughly

### ISSUE THREAD

**Issue by bkircher** [gridscale/terraform-provider-gridscale#98]
Follow-up from PR #97 . As I understood from you that the firewall handling has been changed since v1.7.1. Before v1.7.1, all ports are open by default, so the customer did not need to add firewall rules to the network attached to a server to open specific ports. After v1.7.1, all ports are close by default, so the customer should add a firewall rule to open a specific port e.g., 22, and add the firewall rule to the network attached to a server. It would be great to document this changing behavior and give some examples.

**Comment by bkircher** [comment]
@itakouna  FYI

**Comment by nvthongswansea** [comment]
Done in [PR 101](https://github.com/gridscale/terraform-provider-gridscale/pull/101)
